etcd:
  image: quay.io/coreos/etcd:v2.2.5
  ports:
    - "4001:4001"
  command: >
    --listen-client-urls 'http://localhost:2379,http://0.0.0.0:4001'
    --advertise-client-urls 'http://localhost:2379,http://192.168.99.100:4001'

lb:
  image: nginx-lb
  environment:
    - "ETCD_ADDR=http://192.168.99.100:4001"
    - "ETCD_INTERVAL=10"
  ports:
   - "80:80"
